package com.ginni.quiz_service.service;


import com.ginni.quiz_service.dao.QuizDao;
import com.ginni.quiz_service.feign.QuizInterface;
import com.ginni.quiz_service.model.QuestionWrapper;
import com.ginni.quiz_service.model.Quiz;
import com.ginni.quiz_service.model.Response;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

//mapping b/w quiz table and question table--> manyto many as 2 quiz can have a similar question
//service responsibility to create a quizfor me
@Service
public class QuizService {

    @Autowired
    QuizDao quizDao;
//    @Autowired
//    QuestionDao questionDao;

    //Quiz interface used to make all the calls
    @Autowired
    QuizInterface quizInterface;

    public ResponseEntity<String> createQuiz(String category, int noOfQuestions, String title) {
        //dao layer giving the ques it comes from question-daoo and cannot use findAll() as it would return all
//        List<Question> questions = questionDao.findRandomQuestionsByCategory(category,noOfQuestions);
//--------this time we don't want questions data, we just want the question no./id / list of integer
//--------questionDao.findRandomQuestionsByCategory(category,noOfQuestions); won't work, instead we want
// ----to call getQuestionsForQuiz and "generate" url from question service, basically send reuest
        List<Integer> questions= quizInterface.getQuestionsForQuiz(category,noOfQuestions).getBody();
// ----from Quiz-service(QS)  to Question-service(QueS)- by using RestTemplate class
// ----send arequest to QueS- http://localhost:8080/question/generate - localhost means same machine but Microservs
//----can be built on othermachine and dont want to put IP address and hardcode port nums there4 for intracting
// ----of 2 different service - Feign Client is needed(Notes) - reuqest usimg servicename(naming server)
//----2ndly-QS search for QueS, so QueS needs to be discovered - so using other Service- Start Discovery
//----to discover API or servis we need server- Eureka Server(See Copy of its usage)
//        //to create quiz
        Quiz quiz = new Quiz();
//        //id is autogenerated
        quiz.setTitle(title);
       quiz.setQuestionIds(questions);
       quizDao.save(quiz);
//
//        //using quizdao to save
//        quizDao.save(quiz);
//        //return response
        return new ResponseEntity<>("Success", HttpStatus.CREATED);
    }

    public ResponseEntity<List<QuestionWrapper>> getQuizQuestions(Integer id) {
        //ideally Quiz quiz=quizDao......but when valid id is not there than null error can be avoided
        //this return question making quiz object
//        Optional<Quiz> quiz = quizDao.findById(id);
        Quiz quiz = quizDao.findById(id).get();
        List<Integer> questionids = quiz.getQuestionIds();
        ResponseEntity<List<QuestionWrapper>> questions = quizInterface.getQuestionsFormId(questionids);
        return questions;
//        List<Question> questionFormDB = quiz.get().getQuestions();
//
//        //we want to convet question to question wrapper
        //List<QuestionWrapper> questionForUser = new ArrayList<>();
//        // questionForUser is empty at this point we need to add it from questionFormDB
//        for(Question q:questionFormDB){
//            QuestionWrapper qw  = new QuestionWrapper(q.getId(),q.getQuestionTitle(),q.getOption1(),q.getOption2(),q.getOption3(),q.getOption4());
//
//            questionForUser.add(qw);
//        }
        //return new ResponseEntity<>(questionForUser,HttpStatus.OK);

    }
    //write logic to calculate result
    public ResponseEntity<Integer> calculateResult(Integer id, List<Response> responses) {
//        Quiz quiz = quizDao.findById(id).get(); //get the quiz
//        List<Question> questions = quiz.getQuestions();  //get the ques fromquiz id and put in list
//        //now compare values in responses and questions above
       // int right =0;
//        int i=0;
//        for(Response r : responses){
//            if(r.getResponse().equals(questions.get(i).getRightAnswer()))
//                right++;
//            i++;
         ResponseEntity<Integer> score =quizInterface.getScore(responses);
         return score;
//
//        }
       // return new ResponseEntity<>(right,HttpStatus.OK);
    }
}
